# Generated by Django 2.2.13 on 2022-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_zone',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateField(),
        ),
    ]
